localPath = scriptPath()
imagePath = (localPath .. "image/")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/inventory4.png", imagePath .."inventory4.png")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/inventory5.png", imagePath .."inventory5.png")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/inventory2.png", imagePath .."inventory2.png")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/inventory3.png", imagePath .."inventory3.png")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/inventory1.png", imagePath .."inventory1.png")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/complete_all_zero.png", imagePath .."complete_all_zero.png")
