localPath = scriptPath()
imagePath = (localPath .. "image/")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/camp_view.png", imagePath .."camp_view.png")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/ancient_guardian.png", imagePath .."ancient_guardian.png")
httpDownload("https://raw.githubusercontent.com/iamafkbot/BDMafk/master/image/home2.png", imagePath .."home2.png")
